### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by TimB87** [davedufresne/modern_snmp#1]
Hi @davedufresne 👋 

I wanted to try out modern_snmp but it fails to build for me:

```
modern_snmp on  master via 🦀 v1.67.0
❯ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `aes-soft = "^0.4"`
candidate versions found which didn't match: 0.99.99, 0.6.4, 0.6.3, ...
location searched: crates.io index
required by package `aes v0.4.0`
    ... which satisfies dependency `aes = "^0.4.0"` of package `snmp_usm v0.2.0 (C:\Users\bierma_t\git\modern_snmp\src\snmp_usm)`
```

**Comment by davedufresne** [comment]
Hi @TimB87 , thanks for the heads-up. I'll update the dependencies and let you know when I'm done.

**Comment by TimB87** [comment]
@davedufresne Thanks a lot for taking this up, I gave it a shot already but this is a bit above me.

`aes` needs to be at least at version 0.6.0, then I had problems with the BlockCipher implementation.
Please let me know if I can be of any help here :)

**Comment by davedufresne** [comment]
Hi @TimB87 , I just pushed an updated version that compiles. Have a good day!

**Comment by TimB87** [comment]
Hi @davedufresne 
Works perfectly fine! Thank you so much!
